import re

SKILLS = ("linux", "shell", "processes", "systemd", "networking", "dns", "wifi", "packets", "web", "git", "rescue")

COMMAND_BOOK = {
    "ls": ("Lists directory contents.", "Linux foundations"),
    "grep": ("Finds lines matching a pattern.", "Pipes"),
    "chmod": ("Changes file permission bits.", "Permissions"),
    "findmnt": ("Shows which filesystem backs a path.", "Linux foundations"),
    "stat": ("Shows file type, ownership, and metadata.", "Linux foundations"),
    "printf": ("Writes predictable formatted text.", "Pipes"),
    "sort": ("Orders lines of text.", "Pipes"),
    "uniq": ("Collapses or counts adjacent duplicate lines.", "Pipes"),
    "wc": ("Counts lines, words, or bytes.", "Pipes"),
    "ps": ("Shows running process information.", "Processes"),
    "kill": ("Sends a signal to a process.", "Processes"),
    "systemctl": ("Inspects and controls systemd units.", "systemd and logs"),
    "journalctl": ("Reads the systemd journal.", "systemd and logs"),
    "ip": ("Shows and changes network interfaces and routes.", "Networking"),
    "ss": ("Shows socket and connection state.", "DNS, routes, and sockets"),
    "dig": ("Queries DNS servers and records.", "DNS, routes, and sockets"),
    "getent": ("Queries system name-service databases.", "DNS, routes, and sockets"),
    "ssh": ("Opens secure remote shell connections.", "SSH"),
    "iw": ("Shows Linux wireless interfaces and radio state.", "Wi-Fi fundamentals"),
    "nmcli": ("Inspects and controls NetworkManager.", "Wi-Fi fundamentals"),
    "lsusb": ("Lists USB devices and their identifiers.", "Wi-Fi fundamentals"),
    "ethtool": ("Shows network driver and link details.", "Wi-Fi fundamentals"),
    "nmap": ("Discovers hosts and exposed network services.", "Safe reconnaissance"),
    "tcpdump": ("Captures and displays network packets.", "Packet analysis"),
    "curl": ("Sends requests to URLs and shows responses.", "Web-security lab"),
    "strace": ("Shows system calls made by a process.", "Cool Linux Thing: strace"),
    "lsof": ("Lists files and sockets opened by processes.", "Cool Linux Thing: lsof"),
    "tmux": ("Runs persistent, multiplexed terminal sessions.", "Cool Linux Thing: tmux"),
    "readlink": ("Shows the target of a symbolic link.", "Linux internals"),
    "git": ("Tracks and compares source history.", "Git as a safety net"),
    "docker": ("Runs and manages isolated containers.", "Cyber range"),
    "lsblk": ("Lists block devices without modifying them.", "PC rescue"),
    "inxi": ("Summarizes hardware, drivers, and system state.", "Pip's Rescue Bay"),
    "smartctl": ("Reads drive identity and SMART health evidence.", "Pip's Rescue Bay"),
    "nvme": ("Reads NVMe controller and health information.", "Pip's Rescue Bay"),
    "dmesg": ("Reads kernel messages about hardware and drivers.", "Pip's Rescue Bay"),
    "memtester": ("Tests an explicitly chosen amount of allocated RAM.", "Pip's Rescue Bay"),
    "testdisk": ("Interactively investigates partitions and filesystems.", "Pip's Rescue Bay"),
    "photorec": ("Recovers recognized files to separate destination storage.", "Pip's Rescue Bay"),
    "ddrescue": ("Copies readable data from a failing source using a persistent mapfile.", "Pip's Rescue Bay"),
    "gparted": ("Interactively inspects and edits disk partitions.", "Pip's Rescue Bay"),
    "ufw": ("Manages a host firewall with readable allow/deny policies.", "Privacy Mode"),
    "hostnamectl": ("Reads or changes the system hostname.", "Privacy Mode"),
    "tailscale": ("Shows private Tailscale network status.", "Privacy Mode"),
    "resolvectl": ("Shows systemd-resolved DNS state.", "Wi-Fi lab"),
}

def command_names(command):
    words = set(re.findall(r"[A-Za-z][A-Za-z0-9-]*", command))
    return [name for name in COMMAND_BOOK if name in words]

def mission(id, title, skill, xp, concepts, intro, mental, step, challenge, *, answers=(), answer_pattern=None, output_pattern=None, side=False):
    return {
        "id": id, "title": title, "skill": skill, "xp": xp, "concepts": concepts,
        "intro": intro, "mental_model": mental,
        "steps": [{"command": step[0], "commands": command_names(step[0]), "observe": step[1], "explanation": step[2]}],
        "challenge": {
            "command": challenge[0], "question": challenge[1], "hint": challenge[2],
            "answers": list(answers), "answer_pattern": answer_pattern, "output_pattern": output_pattern,
            "explanation": challenge[3], "commands": command_names(challenge[0]),
        },
        "side": side,
    }

LESSONS = [
    mission("filesystem", "Linux foundations", "linux", 60, ["linux.filesystem"],
        "You know cd and ls; now map the tree underneath them.", "Linux mounts filesystems into one tree rooted at /.",
        ("findmnt /", "What source and filesystem back /?", "findmnt connects a path to its mounted device and filesystem."),
        ("stat -c '%F' /etc/passwd", "What file type did stat report?", "Use the first words from the output.", "Linux treats many resources like files, but stat reveals the actual type."), answers=("regular file",)),
    mission("permissions", "Permissions", "linux", 70, ["linux.permissions"],
        "Permissions answer who may read, change, or execute.", "Mode bits are three decisions for owner, group, and everyone else.",
        ("stat -c '%A %U %G' /etc/passwd", "Which fields show mode, owner, and group?", "stat shows evidence without changing permissions."),
        ("test -r /etc/passwd && echo readable", "What did the access check print?", "test checks access without modifying the file.", "A successful test proves your current user can read the file."), answers=("readable",)),
    mission("pipes", "Pipes", "shell", 75, ["shell.pipes"],
        "A pipe sends one program's output into another.", "Small filters compose: producer | transformer | counter.",
        (r"printf 'beta\nalpha\nbeta\n' | sort | uniq -c", "What changed after sort and uniq?", "sort groups equal lines so uniq can count them."),
        (r"printf 'one\ntwo\nthree\n' | wc -l", "How many lines reached wc?", "Count the newline-terminated records.", "wc -l counts lines received through standard input."), answers=("3",)),
    mission("processes", "Processes", "processes", 80, ["processes.signals"],
        "A process is a running program with an ID and parent.", "Signals are messages; TERM asks cleanly, KILL gives no cleanup chance.",
        ("ps -o pid,ppid,comm -p $$", "Which PID is the shell and which is its parent?", "PID identifies this shell; PPID identifies who launched it."),
        ("kill -l TERM", "What signal number is TERM?", "Ask kill to translate the signal name.", "SIGTERM is the normal first request to stop."), answers=("15",)),
    mission("systemd", "systemd and logs", "systemd", 90, ["systemd.services", "systemd.logs"],
        "Services have state; the journal records why that state changed.", "systemctl asks about units; journalctl asks about events.",
        ("systemctl list-units --type=service --state=running --no-pager | head -5", "What makes a service 'running' here?", "The active state is current runtime evidence, not a boot promise."),
        ("journalctl -b -n 1 --no-pager", "Which flag limits logs to this boot?", "Look at the command before the output.", "-b selects the current boot; -n limits the number of entries."), answers=("-b", "b")),
    mission("networking", "Networking", "networking", 95, ["networking.interfaces"],
        "Start with interfaces and addresses before blaming DNS.", "An interface connects a network; an address identifies this host on it.",
        ("ip -brief address", "Which interfaces are up and which have addresses?", "ip -brief compresses link state and addresses into evidence you can scan."),
        ("ip -o link show lo", "Which interface is the loopback device?", "The challenge names one safe local interface.", "lo is the host's loopback interface; its traffic never leaves the machine."), answers=("lo",)),
    mission("dns-routes-sockets", "DNS, routes, and sockets", "dns", 110, ["networking.routing", "networking.dns", "networking.sockets", "dns.resolution"],
        "Name lookup, path choice, and open sockets are separate layers.", "DNS maps names, routes choose next hops, sockets join addresses to ports.",
        ("ip route show default; getent hosts localhost; ss -lnt | head -5", "Which output belongs to routes, DNS, and sockets?", "Read the three outputs as separate stages, not one vague 'network'."),
        ("getent hosts localhost", "What first address resolved for localhost?", "Copy the first field.", "getent uses the system resolver path applications normally use."), answer_pattern=r"(?m)^(\S+)"),
    mission("ssh", "SSH", "networking", 105, ["networking.ssh"],
        "SSH securely connects a client to a remote shell.", "Host keys identify servers; user keys authenticate people or machines.",
        ("ssh -V", "Was this the SSH client or server program?", "ssh is the client; sshd is the server daemon."),
        ("ssh -G localhost | awk '$1==\"hostname\"{print $2; exit}'", "What hostname will SSH use?", "Copy the resolved hostname.", "ssh -G expands configuration without opening a connection."), answers=("localhost",)),
    mission("linux-internals", "Linux internals", "linux", 120, ["linux.internals", "linux.proc", "linux.sys"],
        "/proc and /sys expose live kernel state as navigable files.", "/proc focuses on processes; /sys focuses on devices and kernel objects.",
        ("head -5 /proc/self/status", "Which process does self refer to?", "self follows the process reading /proc, so it changes by caller."),
        ("test -d /sys/class/net && echo kernel-devices", "What did the safe directory check print?", "Check the output exactly.", "/sys/class/net represents network devices through the kernel object model."), answers=("kernel-devices",)),
    mission("git", "Git as a safety net", "git", 100, ["git.workflow"],
        "Git records snapshots so experiments remain explainable and reversible.", "status shows state, diff shows change, commit names a reviewed snapshot.",
        ("git --version", "Which Git program is installed?", "The version proves the client exists; it does not change a repository."),
        ("git help -a | grep -w status | head -1", "Which command inspects working-tree state?", "Read the command name in the output.", "git status is the safe first check before editing or committing."), answers=("status", "git status"), output_pattern=r"status"),
    mission("wifi", "Wi-Fi fundamentals", "wifi", 120, ["wifi.interfaces", "wifi.channels"],
        "Trace Wi-Fi from USB hardware to driver to interface to radio link.", "A visible adapter is not necessarily connected; link state supplies channel and signal evidence.",
        ("iw dev", "Which wireless interfaces and channels are visible?", "iw reads kernel wireless state without transmitting attacks."),
        ("iw dev | awk '$1==\"Interface\"{print $2}'", "Enter one wireless interface name.", "Attach the Panda adapter if the command is empty.", "Interface names come from the kernel; never guess them."), answer_pattern=r"(?m)^(\S+)$"),
    mission("packets", "Packet analysis", "packets", 130, ["packets.capture", "packets.ports"],
        "Packets are evidence about conversations between endpoints.", "Addresses locate hosts; ports identify services; flags describe protocol state.",
        ("ip -s link show lo", "Which counters increase when loopback traffic moves?", "RX receives and TX transmits; counters are observations, not causes."),
        ("ss -lntu | head -5", "Which command listed listening TCP/UDP sockets?", "The command is shown above the output.", "ss reads socket state without probing another host."), answers=("ss", "ss -lntu")),
    mission("reconnaissance", "Safe reconnaissance", "packets", 140, ["packets.recon"],
        "Reconnaissance asks what is reachable before testing anything deeper.", "Scope first: this mission scans only your own loopback host.",
        ("nmap -sn 127.0.0.1", "What did host discovery say about loopback?", "-sn checks host availability without a port scan."),
        ("nmap -sT -p 22,80 127.0.0.1", "Which host did you scan?", "Read the explicitly scoped target.", "A TCP connect scan reports service reachability; it does not prove vulnerability."), answers=("127.0.0.1", "localhost"), output_pattern=r"Nmap done"),
    mission("web-security", "Web-security lab", "web", 150, ["web.http", "web.security"],
        "Web testing starts with requests, responses, and explicit lab scope.", "HTTP status and headers describe application behavior; they are not vulnerabilities by themselves.",
        ("curl --max-time 5 -sI http://127.0.0.1:3000 | head -1", "Which HTTP status did the local lab return?", "Run labctl web first if no local response appears."),
        (r"curl --max-time 5 -s -o /dev/null -w '%{http_code}\n' http://127.0.0.1:3000", "Enter the HTTP status code.", "Start the isolated web lab with labctl web.", "curl measures the local lab response without attacking an external service."), answer_pattern=r"(?m)^(\d{3})$"),
    mission("rescue", "PC rescue", "rescue", 150, ["rescue.storage", "rescue.evidence"],
        "Rescue begins with identification and evidence, not writes.", "Model, size, transport, mounts, and health logs prevent wrong-disk mistakes.",
        ("lsblk -o NAME,SIZE,TYPE,TRAN", "Which entries are disks and which are partitions?", "TYPE separates whole disks from partitions; TRAN shows attachment type."),
        ("findmnt -no SOURCE /", "Which source contains the running root filesystem?", "Copy the exact source path.", "findmnt identifies the mounted source without changing any disk."), answer_pattern=r"(?m)^(\S+)$"),
]

SIDE_MISSIONS = [
    mission("cool-proc", "Cool Linux Thing: /proc", "linux", 35, ["linux.proc"], "Peek at live process state.", "/proc is a kernel-generated view, not stored files.",
        ("grep '^Name:' /proc/self/status", "What process name appeared?", "self means the reader of this virtual file."),
        ("readlink /proc/self/exe", "What executable path appeared?", "Copy the path.", "The exe link points at the running program."), answer_pattern=r"(?m)^(.+)$", side=True),
    mission("cool-sys", "Cool Linux Thing: /sys", "linux", 35, ["linux.sys"], "Inspect kernel device classes.", "/sys organizes devices by kernel relationships.",
        ("ls /sys/class/net", "Which network devices appeared?", "These names come from registered kernel devices."),
        ("test -d /sys/class/net/lo && echo loopback", "What did the check print?", "Check the output.", "The loopback device exists in the network class."), answers=("loopback",), side=True),
    mission("cool-fds", "Cool Linux Thing: file descriptors", "processes", 35, ["processes.file_descriptors"], "See how processes refer to open resources.", "File descriptors are small numbers indexing a process's open files and streams.",
        ("ls -l /proc/$$/fd", "Where do descriptors 0, 1, and 2 point?", "They normally represent input, output, and errors."),
        ("readlink /proc/$$/fd/1", "Where does standard output point?", "Copy the target.", "Descriptor 1 is standard output and may be a terminal or pipe."), answer_pattern=r"(?m)^(.+)$", side=True),
    mission("cool-signals", "Cool Linux Thing: signals", "processes", 35, ["processes.signals"], "Translate signal names safely.", "Signals request process actions; handlers decide whether cleanup is possible.",
        ("kill -l TERM", "Which number maps to TERM?", "Translation sends no signal."),
        ("kill -l INT", "Which number maps to INT?", "Ask kill to translate INT.", "SIGINT is commonly generated by Ctrl-C."), answers=("2",), side=True),
    mission("cool-namespaces", "Cool Linux Thing: namespaces", "processes", 35, ["processes.namespaces"], "Inspect process isolation boundaries.", "Namespaces give processes different views of IDs, mounts, networks, and more.",
        ("readlink /proc/self/ns/pid", "What namespace identifier appeared?", "The bracketed inode identifies the PID namespace."),
        ("readlink /proc/self/ns/mnt", "What mount namespace identifier appeared?", "Copy the complete link target.", "Different identifiers mean different isolated views."), answer_pattern=r"(?m)^(.+)$", side=True),
    mission("cool-strace", "Cool Linux Thing: strace", "processes", 35, ["processes.strace"], "Watch a program ask the kernel for work.", "strace shows system calls at the user/kernel boundary.",
        ("strace -c true 2>&1 | tail -5", "Which calls did even true need?", "A tiny command still loads, maps memory, and exits through the kernel."),
        ("strace -e write echo pip 2>&1 | grep 'write(' | head -1", "Which syscall emitted text?", "Read the syscall name.", "write sends bytes to a file descriptor."), answers=("write", "write()"), output_pattern=r"write\(", side=True),
    mission("cool-lsof", "Cool Linux Thing: lsof", "processes", 35, ["processes.file_descriptors"], "List a process's open resources.", "lsof joins processes, descriptors, sockets, and files in one view.",
        ("lsof -p $$ | head -5", "Which resources belong to this shell?", "-p limits evidence to one PID."),
        ("lsof -a -p $$ -d cwd -Fn | tail -1", "Which directory is the shell using?", "Remove the leading n when answering.", "cwd is the process's current working directory descriptor."), answer_pattern=r"(?m)^n(.+)$", side=True),
    mission("cool-tmux", "Cool Linux Thing: tmux", "shell", 35, ["shell.tmux"], "Discover the terminal multiplexer already installed.", "tmux keeps terminal sessions alive independently of one window.",
        ("tmux -V", "Which tmux version is installed?", "This is read-only discovery."),
        ("tmux list-commands | grep '^new-session' | head -1", "Which command creates a session?", "Read the first command name.", "new-session starts an independent terminal workspace."), answers=("new-session",), output_pattern=r"new-session", side=True),
    mission("cool-sockets", "Cool Linux Thing: sockets", "networking", 35, ["networking.sockets"], "Inspect local listening endpoints.", "A socket binds protocol, address, and port to a process conversation.",
        ("ss -lnt | head -5", "Which local addresses and ports are listening?", "-l means listening, -n avoids name guessing, -t selects TCP."),
        ("ss -H -lnt | wc -l", "How many listening TCP sockets were counted?", "Copy the number.", "Removing headers makes wc count only socket rows."), answer_pattern=r"(?m)^\s*(\d+)\s*$", side=True),
    mission("cool-mounts", "Cool Linux Thing: mounts", "linux", 35, ["linux.mounts"], "Connect paths to filesystems.", "A mount attaches a filesystem at a directory in the one Linux tree.",
        ("findmnt /", "Which source and type back /?", "The target path is evidence of where a filesystem is attached."),
        ("findmnt -no FSTYPE /", "Which filesystem type backs /?", "Copy the type.", "-n removes headings and -o selects one field."), answer_pattern=r"(?m)^(\S+)$", side=True),
]

LAB_QUESTS = [
    {"id": "lab-discover-ip", "title": "Range: Discover Target IP", "xp": 45, "skill": "networking", "concepts": ["networking.addressing"], "lab_quest": 1,
     "objective": "Resolve the isolated target's IP address.", "hint": "Container DNS maps its name to an address inside the range."},
    {"id": "lab-ping", "title": "Range: Ping Target", "xp": 45, "skill": "networking", "concepts": ["networking.icmp"], "lab_quest": 2,
     "objective": "Verify that the isolated target answers ICMP.", "hint": "Ping reveals reachability and round-trip timing, not whether every service works."},
    {"id": "lab-scan", "title": "Range: Scan Ports", "xp": 60, "skill": "packets", "concepts": ["packets.ports"], "lab_quest": 3,
     "objective": "Find the target's exposed TCP service.", "hint": "A port scan asks which transport endpoints answer."},
    {"id": "lab-http", "title": "Range: Identify HTTP", "xp": 55, "skill": "web", "concepts": ["web.http"], "lab_quest": 4,
     "objective": "Request the target page and identify the service response.", "hint": "An HTTP client shows application-layer content."},
    {"id": "lab-headers", "title": "Range: Inspect Headers", "xp": 55, "skill": "web", "concepts": ["web.http"], "lab_quest": 5,
     "objective": "Inspect HTTP response metadata without downloading the page body.", "hint": "Headers reveal status and server metadata, not proof of a vulnerability."},
    {"id": "lab-capture", "title": "Range: Capture Your Packets", "xp": 70, "skill": "packets", "concepts": ["packets.capture"], "lab_quest": 6,
     "objective": "Capture only the ICMP packets generated by your own lab ping.", "hint": "A capture turns packet exchange into evidence you can inspect."},
    {"id": "lab-broken-http", "title": "Range: Broken Service", "xp": 75, "skill": "networking", "concepts": ["networking.sockets"], "lab_quest": 7,
     "objective": "Diagnose an intentionally stopped HTTP service.", "hint": "A reachable host can still have a closed service port."},
    {"id": "lab-permissions", "title": "Range: Permissions Repair", "xp": 75, "skill": "linux", "concepts": ["linux.permissions"], "lab_quest": 8,
     "objective": "Repair an intentionally unreadable file inside the disposable target.", "hint": "Owner read/write permission is enough; avoid making it world-writable."},
]

QUESTS = LAB_QUESTS + [
    {"id": "mystery-port", "title": "Mystery Port", "xp": 120, "skill": "packets", "concepts": ["packets.ports"],
     "objective": "Start the Academy range, discover the target, identify a listening service and explain what an open port represents.",
     "hint": "Start with labctl start, enter the tools container, then choose a TCP port enumeration tool."},
    {"id": "route-detective", "title": "Route Detective", "xp": 90, "skill": "networking", "concepts": ["networking.routing"],
     "verify": {"command": ["ip", "route", "show", "default"], "pattern": r"default via (\S+)", "prompt": "Default gateway"},
     "objective": "Find your default gateway and explain how Linux decides where Internet-bound traffic goes.",
     "hint": "The routing table is more useful than the IP-address list."},
    {"id": "service-mechanic", "title": "Service Mechanic", "xp": 110, "skill": "systemd", "concepts": ["systemd.services"],
     "objective": "Inspect Ollama, find current-boot logs, and explain start versus enable.",
     "hint": "systemd has one tool for unit state and another for its journal."},
    {"id": "radio-operator", "title": "Radio Operator", "xp": 130, "skill": "wifi", "concepts": ["wifi.interfaces"],
     "verify": {"command": ["iw", "dev"], "pattern": r"Interface (\S+)", "prompt": "Panda wireless interface"},
     "objective": "Identify the Panda USB ID, interface, driver, and current band/channel.",
     "hint": "Use wifi-lab interfaces and follow hardware -> driver -> interface."},
]
